global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_server'
    static_configs:
      - targets: ['api_server:8001']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']
    metrics_path: /metrics
    params:
      format: [prometheus]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mongodb_exporter:9216
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: "jenkins_job"
    metrics_path: /prometheus/
    static_configs:
      - targets: ["51.103.212.197:8080"]
